In [1]:
#Importing relevant libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

#Reading the dataset and splitting features from classes
iris = pd.read_csv('iris.data', header=None)
#X = iris.iloc[:, :2]
X = iris.iloc[:, :-1]
y = iris.iloc[:, -1]

#Splitting test set from training set
X, X_test, y, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

#Calculating probability density
def calculate_gaussian_p(x, w, mean, std):
    prob = []
    for i in range(len(w)):
        arr = []
        for j in range(len(x)):
            arr.append(1 / (std[i][j] * np.sqrt(2 * np.pi)) * np.e ** (-0.5 * ((x[j] - mean[i][j]) / std[i][j]) ** 2))
        prob.append(arr)

    
    return prob

#Normalizing probabilities
def calculate_probability(p):
    probability = []
    likelyhood_sum = 0
    for i in range(len(p)):
        prob = 1
        for j in range(len(p[0])):
            prob *= p[i][j]
        probability.append(prob)
        
    likelyhood_sum = sum(probability)
    for i in range(len(probability)):
        probability[i] = probability[i] / likelyhood_sum
    return probability

#Function for prediction based on probabilities for each class
def predict(res):
    return classes[np.argmax(res)]

#Calculating standard deviations and mean
classes = np.unique(y)
group = [X[y == i] for i in classes]

mean = [np.mean(c, axis=0) for c in group]
std = [np.std(c, axis=0) for c in group]

In [2]:
#Initializing a list for storing predictions
predictions = []

#Making predictions for the test set
for x_test in X_test.iloc:
    prob = calculate_gaussian_p(x_test, classes, mean, std)
    dist = calculate_probability(prob)
    predictions.append(predict(dist))

In [3]:
#Printing a cunfusion matrix and accuracy based on comparison of the predictions and the test set
cm = confusion_matrix(y_test, predictions)
accuracy = cm.diagonal().sum() / cm.sum()
print("Confusion Matrix: \n", cm)
print("Accuracy: ", accuracy)

Confusion Matrix: 
 [[16  0  0]
 [ 0 18  0]
 [ 0  1 10]]
Accuracy:  0.9777777777777777
